# Generated by Django 4.2.7 on 2025-05-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.BooleanField(default=False),
            
        ),
    ]
