# Generated by Django 4.2.7 on 2025-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_appointment_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
